// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToughService.Data;

#nullable disable

namespace ToughService.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ToughService.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ToughService.Models.ChamadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataDesejada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoExtintor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("ToughService.Models.ItemCarrinhoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UserId");

                    b.ToTable("ItensCarrinho");
                });

            modelBuilder.Entity("ToughService.Models.PedidoItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("ToughService.Models.PedidoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CustoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MetodoEnvio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.ProdutoBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sku_Agente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku_Capacidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku_Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku_Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Produtos", (string)null);

                    b.HasDiscriminator<string>("TipoProduto").HasValue("ProdutoBaseModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ToughService.Models.ProdutoModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Peso")
                                .HasColumnName("ProdutoModel_Peso");
                        });

                    b.HasDiscriminator().HasValue("Generico");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.AcessorioModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Dimensoes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoAcessorio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Dimensoes")
                                .HasColumnName("AcessorioModel_Dimensoes");

                            t.Property("Material")
                                .HasColumnName("AcessorioModel_Material");
                        });

                    b.HasDiscriminator().HasValue("Acessorio");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.EPCModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("AreaProtecao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dimensoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEPC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Material")
                                .HasColumnName("EPCModel_Material");

                            t.Property("Norma")
                                .HasColumnName("EPCModel_Norma");
                        });

                    b.HasDiscriminator().HasValue("EPC");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.EPIModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("CertificacaoCA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEPI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("CertificacaoCA")
                                .HasColumnName("EPIModel_CertificacaoCA");

                            t.Property("Material")
                                .HasColumnName("EPIModel_Material");

                            t.Property("Norma")
                                .HasColumnName("EPIModel_Norma");

                            t.Property("Tamanho")
                                .HasColumnName("EPIModel_Tamanho");
                        });

                    b.HasDiscriminator().HasValue("EPI");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.EPRModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("CertificacaoCA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEPR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoFiltro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Norma")
                                .HasColumnName("EPRModel_Norma");
                        });

                    b.HasDiscriminator().HasValue("EPR");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.EquipamentoArMandadoModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("Capacidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Potencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PressaoTrabalho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEquipamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Capacidade")
                                .HasColumnName("EquipamentoArMandadoModel_Capacidade");

                            t.Property("PressaoTrabalho")
                                .HasColumnName("EquipamentoArMandadoModel_PressaoTrabalho");
                        });

                    b.HasDiscriminator().HasValue("ArMandado");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.ExtintorModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("Capacidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRecarga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormaReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoAgente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Extintor");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.HidranteModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PressaoTrabalho")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Rosca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoHidrante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Material")
                                .HasColumnName("HidranteModel_Material");
                        });

                    b.HasDiscriminator().HasValue("Hidrante");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.MangueiraModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Diametro")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasDiscriminator().HasValue("Mangueira");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.PortaCortaFogoModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Certificacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TempoResistenciaFogo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoAbertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("PortaCortaFogo");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.SistemaDeteccaoModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("AreaCobertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TensaoAlimentacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDetecao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Norma")
                                .HasColumnName("SistemaDeteccaoModel_Norma");
                        });

                    b.HasDiscriminator().HasValue("SistemaDeteccao");
                });

            modelBuilder.Entity("ToughService.Models.Produtos.SistemaFixoModel", b =>
                {
                    b.HasBaseType("ToughService.Models.Produtos.ProdutoBaseModel");

                    b.Property<string>("AreaCobertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CapacidadeSistema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSistema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("AreaCobertura")
                                .HasColumnName("SistemaFixoModel_AreaCobertura");
                        });

                    b.HasDiscriminator().HasValue("SistemaFixo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ToughService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ToughService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToughService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ToughService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToughService.Models.ChamadoModel", b =>
                {
                    b.HasOne("ToughService.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToughService.Models.ItemCarrinhoModel", b =>
                {
                    b.HasOne("ToughService.Models.Produtos.ProdutoBaseModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToughService.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToughService.Models.PedidoItemModel", b =>
                {
                    b.HasOne("ToughService.Models.PedidoModel", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToughService.Models.Produtos.ProdutoBaseModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ToughService.Models.PedidoModel", b =>
                {
                    b.HasOne("ToughService.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToughService.Models.PedidoModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
